services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
  
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    secrets:
      - db_password
      - wp_admin_pass
      - wp_user_pass
  
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception
    secrets:
      - db_password
      - db_root_password

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/${INCEPTION_LOGIN}/data/mariadb_data"
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/${INCEPTION_LOGIN}/data/wordpress_data"

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_pass.txt
  wp_user_pass:
    file: ../secrets/wp_user_pass.txt